# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [13]:
import numpy as np

2. Create a null vector of size 10 

In [10]:
v = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [11]:
v = np.arange(10,50)

4. Find the shape of previous array in question 3

In [17]:
v.shape

(40,)

5. Print the type of the previous array in question 3

In [23]:
v.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [28]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tjamil/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tjamil/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tjamil/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tjamil/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tjamil/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tjamil/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/tjamil/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/tjamil/anaconda3/include']
None


7. Print the dimension of the array in question 3


In [29]:
print (v.ndim)

1


8. Create a boolean array with all the True values

In [32]:
x = np.full((10,10), True, dtype=bool)
x

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

9. Create a two dimensional array




In [35]:
xy = np.empty((10,10))

10. Create a three dimensional array



In [37]:
xyz = np.empty((2,3,4))

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [40]:
v = np.array([2,4,7,9,99])
reverse_v = v[::-1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [6]:
vx = np.zeros(10)
vx[4]=1
vx

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [12]:
m2d = np.identity(3)
m2d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [18]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = arr.astype('float64')
arr1

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [20]:
arr1 = np.array([[1., 2., 3.],

                [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

               [7., 2., 12.]])


arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [21]:
arr1 = np.array([[1., 2., 3.],

                [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

                [7., 2., 12.]])

arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [27]:
array1 = np.arange(10)
array1 [array1 % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [28]:
array1 [array1 % 2 == 1]=-1
array1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [36]:
array1 [4:8]=12
array1

array([ 0, -1,  2, -1, 12, 12, 12, 12,  8, -1])

20. Create a 2d array with 1 on the border and 0 inside

In [81]:
array_2d = np.ones([5,5])
array_2d[1:-1,1:-1]=0
array_2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [82]:
rr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
rr2d[1:-1,1:-1]=12
rr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [95]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:-1,:-1][:]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [130]:
arr_2D = np.arange(9).reshape(3,3)
sliced_array1 = arr_2D[0, :]
arr_2D
sliced_array1

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [136]:
arr_2D = np.arange(9).reshape(3,3)
sliced_array2 = arr_2D[1,1:-1]
sliced_array2

array([4])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [154]:
arr_2D = np.arange(9).reshape(3,3)

sliced_array3 = arr_2D[:2,2:]
sliced_array3

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [163]:
from numpy import random

arr_rnd = random.randint(100, size=(10, 10))
print(arr_rnd)
mi = np.min(arr_rnd)
ma = np.max(arr_rnd)
print(mi, ma)

[[41 85 25 48 24 66 53 22 93 11]
 [17 79 34 41 71 23  9 96 40 91]
 [ 6 32 30 52 19 89 60 97 59 19]
 [ 5 84 17 13 56 39 77 70 51 97]
 [94 95  6 79  5 80 46  0 83 96]
 [10 93 23 22 47 94 16 65 52 90]
 [96 61 67 65 30 72 29 85 61 74]
 [90 35 73 83 75 90 77 95 72 78]
 [ 4 25 33 40 78 66 65 91 79 49]
 [64 89 28 47 60 92 40 30 39 80]]
0 97


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [165]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [170]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [15]:
array_2D = np.arange(1.,16.).reshape(5,3)
array_2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [21]:
array_3D = np.arange(1.,17.).reshape(2,2,4)
array_3D

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [22]:
array_3D = np.arange(1.,17.).reshape(2,2,4)
np.swapaxes(array_3D,0,2)

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [26]:
array = np.arange(1,10)
arrsq = np.sqrt(array)
arrsq[arrsq<0.5]=0.
arrsq

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
from numpy import random

arr1 = random.randn(12)
arr2 = random.randn(12)
array = np.fmax(arr1,arr2)
print (arr1)
print (arr2)
print (array)

[-0.27527328 -1.38382921  0.31936696  1.17185919 -0.2864122   1.77189408
 -1.23935679 -2.40825102  0.3259031  -0.98838686 -0.5261521  -0.79299296]
[-0.31539062 -1.09304853 -0.69993943 -1.52584586  0.32216934  0.36566712
 -1.06250629  0.30673647 -0.18751703 -0.18168756 -0.25559361  0.89796806]
[-0.27527328 -1.09304853  0.31936696  1.17185919  0.32216934  1.77189408
 -1.06250629  0.30673647  0.3259031  -0.18168756 -0.25559361  0.89796806]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names_unique = np.unique(names)
print (names_unique)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [48]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

a = [i for i in a if i not in b]
print (a)

[1, 2, 3, 4]

38.  Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = numpy.array([[10,10,10]])
    

In [97]:
sample = np.array([[34,43,73],[82,22,12],[53,94,66]])
i=1
sample[:1][:1]

array([[34, 43, 73]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [70]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [67]:
matrix = random.randn(20)
sum=np.sum(matrix)
print (matrix)
print (sum)

[-0.12656873 -1.05359389 -0.1148515   0.61956509  0.27874624  0.06145343
 -0.41584055 -1.15887952 -0.4412584  -0.04918487  0.51363343 -1.59884997
  0.97896383 -1.31071006 -1.19896096 -1.62860426 -0.34210278 -0.36848716
  1.03996555 -1.91281998]
-8.228385059311737
